function [] = plotelement(data)
figure
subplot(3,1,1)
plot(data.time,data.e)
title('CHAMP eccentricity')
xlabel('Time')
ylabel('Eccentricity')
subplot(3,1,2)
plot(data.time,data.a)
title('CHAMP semi-major axis')
xlabel('Time')
ylabel('semi-major axis')
subplot(3,1,3)
plot(data.time,data.b)
title('CHAMP semi-minor axis')
xlabel('Time')
ylabel('semi-minor axis')
datetick('x')
end